name = "Skeleton"
version = "0.0.1"

[deps]
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
DrWatson = "634d3b9d-ee7a-5ddf-bec9-22491ea816e1"

[extras]
Documenter = "e30172f5-a6a5-5a46-863b-614d45cd2de4"

[targets]
test = ["Aqua", "Test"]
document = ["Documenter"]

[compat]
DrWatson = "2.18.0"
julia = "1.11.2"
